server:
  port: 80

#rest_url_prefix: http://localhost:8001 #rest api调用url前缀
rest_url_prefix: http://SPRINGCLOUD-DEPT #使用微服务名称代替url
eureka:
  client:
    register-with-eureka: false #自己不注册
    service-url:                #服务引入地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/